export const mockChatRooms = [
  {
    id: 'room-1',
    name: 'General Discussion',
    description: 'Talk about anything light novel related',
    type: 'general' as const,
    region_id: null,
    novel_id: null,
    created_at: '2024-01-01T00:00:00Z',
    created_by: null,
  },
  {
    id: 'room-2',
    name: 'Japanese Light Novels',
    description: 'Discuss Japanese light novels',
    type: 'region' as const,
    region_id: 1,
    novel_id: null,
    created_at: '2024-01-01T00:00:00Z',
    created_by: null,
  },
  {
    id: 'room-3',
    name: 'Chinese Web Novels',
    description: 'Discuss Chinese web novels',
    type: 'region' as const,
    region_id: 2,
    novel_id: null,
    created_at: '2024-01-01T00:00:00Z',
    created_by: null,
  },
  {
    id: 'room-4',
    name: 'Korean Light Novels',
    description: 'Discuss Korean light novels',
    type: 'region' as const,
    region_id: 3,
    novel_id: null,
    created_at: '2024-01-01T00:00:00Z',
    created_by: null,
  },
]

export const mockChatMessages = [
  {
    id: 'msg-1',
    room_id: 'room-1',
    user_id: null,
    content: 'Welcome to NovelHub! Feel free to discuss your favorite light novels here.',
    is_anonymous: true,
    created_at: new Date(Date.now() - 3600000).toISOString(),
    profiles: null,
  },
  {
    id: 'msg-2',
    room_id: 'room-1',
    user_id: null,
    content: 'Just finished Solo Leveling, it was amazing!',
    is_anonymous: true,
    created_at: new Date(Date.now() - 3000000).toISOString(),
    profiles: null,
  },
  {
    id: 'msg-3',
    room_id: 'room-1',
    user_id: null,
    content: 'Has anyone read Overlord? Thinking of starting it.',
    is_anonymous: true,
    created_at: new Date(Date.now() - 2400000).toISOString(),
    profiles: null,
  },
  {
    id: 'msg-4',
    room_id: 'room-2',
    user_id: null,
    content: 'Mushoku Tensei is a masterpiece!',
    is_anonymous: true,
    created_at: new Date(Date.now() - 1800000).toISOString(),
    profiles: null,
  },
  {
    id: 'msg-5',
    room_id: 'room-3',
    user_id: null,
    content: 'Coiling Dragon was my first cultivation novel. Still one of the best.',
    is_anonymous: true,
    created_at: new Date(Date.now() - 1200000).toISOString(),
    profiles: null,
  },
]
