import { mockRegions } from './regions'
import { mockGenres } from './genres'

export const mockNovels = [
  {
    id: '1',
    title: 'Sword Art Online',
    alternative_titles: ['SAO'],
    author: 'Reki Kawahara',
    region_id: 1,
    summary: 'In the year 2022, virtual reality has progressed by leaps and bounds. A massive online role-playing game called Sword Art Online is launched. With the aid of NerveGear technology, players can control their avatars within the game using nothing but their own thoughts.',
    cover_image_url: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=400&h=600&fit=crop',
    status: 'completed' as const,
    publication_year: 2009,
    total_chapters: 26,
    official_links: [{ name: 'Official Site', url: 'https://example.com' }],
    translation_links: [{ name: 'Fan Translation', url: 'https://example.com' }],
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    created_by: null,
    regions: mockRegions[0],
    novel_genres: [
      { genres: mockGenres[0] },
      { genres: mockGenres[2] },
      { genres: mockGenres[4] },
    ],
  },
  {
    id: '2',
    title: 'Overlord',
    alternative_titles: ['オーバーロード'],
    author: 'Kugane Maruyama',
    region_id: 1,
    summary: 'The final hour of the popular virtual reality game Yggdrasil has come. However, Momonga, a powerful wizard and master of the dark guild Ainz Ooal Gown, decides to spend his last few moments in the game as the servers begin to shut down.',
    cover_image_url: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=400&h=600&fit=crop',
    status: 'ongoing' as const,
    publication_year: 2010,
    total_chapters: 14,
    official_links: [{ name: 'Official Site', url: 'https://example.com' }],
    translation_links: null,
    created_at: '2024-01-02T00:00:00Z',
    updated_at: '2024-01-02T00:00:00Z',
    created_by: null,
    regions: mockRegions[0],
    novel_genres: [
      { genres: mockGenres[0] },
      { genres: mockGenres[2] },
      { genres: mockGenres[9] },
    ],
  },
  {
    id: '3',
    title: 'Coiling Dragon',
    alternative_titles: ['盘龙', 'Panlong'],
    author: 'I Eat Tomatoes',
    region_id: 2,
    summary: 'Empires rise and fall on the Yulan Continent. Saints, immortal beings of unimaginable power, battle using spells and swords, leaving swathes of destruction in their wake. Magical beasts rule the mountains, where the brave venture to test themselves.',
    cover_image_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400&h=600&fit=crop',
    status: 'completed' as const,
    publication_year: 2008,
    total_chapters: 806,
    official_links: null,
    translation_links: [{ name: 'Wuxiaworld', url: 'https://example.com' }],
    created_at: '2024-01-03T00:00:00Z',
    updated_at: '2024-01-03T00:00:00Z',
    created_by: null,
    regions: mockRegions[1],
    novel_genres: [
      { genres: mockGenres[0] },
      { genres: mockGenres[1] },
      { genres: mockGenres[2] },
      { genres: mockGenres[10] },
    ],
  },
  {
    id: '4',
    title: 'Solo Leveling',
    alternative_titles: ['나 혼자만 레벨업', 'Only I Level Up'],
    author: 'Chugong',
    region_id: 3,
    summary: 'Ten years ago, "the Gate" appeared and connected the real world with the realm of magic and monsters. Ordinary men and women received superhuman powers and became known as "Hunters." Sung Jin-Woo is the weakest of the E-rank Hunters.',
    cover_image_url: 'https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=400&h=600&fit=crop',
    status: 'completed' as const,
    publication_year: 2016,
    total_chapters: 270,
    official_links: [{ name: 'Official Site', url: 'https://example.com' }],
    translation_links: [{ name: 'Fan Translation', url: 'https://example.com' }],
    created_at: '2024-01-04T00:00:00Z',
    updated_at: '2024-01-04T00:00:00Z',
    created_by: null,
    regions: mockRegions[2],
    novel_genres: [
      { genres: mockGenres[0] },
      { genres: mockGenres[2] },
      { genres: mockGenres[1] },
    ],
  },
  {
    id: '5',
    title: 'Re:Zero',
    alternative_titles: ['Re:ゼロから始める異世界生活'],
    author: 'Tappei Nagatsuki',
    region_id: 1,
    summary: 'Subaru Natsuki is suddenly summoned to a fantasy world. With no sign of the one who summoned him, he soon befriends a silver-haired girl. When he and the girl are mysteriously killed, Subaru awakens to discover he has the ability to turn back time by dying.',
    cover_image_url: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=600&fit=crop',
    status: 'ongoing' as const,
    publication_year: 2012,
    total_chapters: 28,
    official_links: [{ name: 'Official Site', url: 'https://example.com' }],
    translation_links: [{ name: 'Fan Translation', url: 'https://example.com' }],
    created_at: '2024-01-05T00:00:00Z',
    updated_at: '2024-01-05T00:00:00Z',
    created_by: null,
    regions: mockRegions[0],
    novel_genres: [
      { genres: mockGenres[2] },
      { genres: mockGenres[7] },
      { genres: mockGenres[9] },
      { genres: mockGenres[13] },
    ],
  },
  {
    id: '6',
    title: 'The Beginning After The End',
    alternative_titles: ['TBATE'],
    author: 'TurtleMe',
    region_id: 1,
    summary: 'King Grey has unrivaled strength, wealth, and prestige in a world governed by martial ability. However, solitude lingers closely behind those with great power. Beneath the glamorous exterior of a powerful king lurks the shell of man, devoid of purpose and will.',
    cover_image_url: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400&h=600&fit=crop',
    status: 'ongoing' as const,
    publication_year: 2016,
    total_chapters: 400,
    official_links: [{ name: 'Tapas', url: 'https://example.com' }],
    translation_links: null,
    created_at: '2024-01-06T00:00:00Z',
    updated_at: '2024-01-06T00:00:00Z',
    created_by: null,
    regions: mockRegions[0],
    novel_genres: [
      { genres: mockGenres[0] },
      { genres: mockGenres[2] },
      { genres: mockGenres[9] },
      { genres: mockGenres[1] },
    ],
  },
  {
    id: '7',
    title: 'Martial World',
    alternative_titles: ['武极天下', 'Wu Ji Tian Xia'],
    author: 'Cocooned Cow',
    region_id: 2,
    summary: 'In the Realm of the Gods, countless legends fought over a mysterious cube. After the battle it disappeared into the void. Lin Ming stumbles upon this mystery object and begins his journey to become a hero of the land.',
    cover_image_url: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=400&h=600&fit=crop',
    status: 'completed' as const,
    publication_year: 2013,
    total_chapters: 2266,
    official_links: null,
    translation_links: [{ name: 'Wuxiaworld', url: 'https://example.com' }],
    created_at: '2024-01-07T00:00:00Z',
    updated_at: '2024-01-07T00:00:00Z',
    created_by: null,
    regions: mockRegions[1],
    novel_genres: [
      { genres: mockGenres[0] },
      { genres: mockGenres[11] },
      { genres: mockGenres[10] },
      { genres: mockGenres[3] },
    ],
  },
  {
    id: '8',
    title: 'Omniscient Reader\'s Viewpoint',
    alternative_titles: ['전지적 독자 시점'],
    author: 'Sing Shong',
    region_id: 3,
    summary: 'Dokja was an average office worker whose sole interest was reading his favorite web novel. Then one day the novel becomes reality, and Dokja is the only person who knows how the world will end. He now has the chance to change the course of the story.',
    cover_image_url: 'https://images.unsplash.com/photo-1621351183012-e2f9972dd9bf?w=400&h=600&fit=crop',
    status: 'completed' as const,
    publication_year: 2018,
    total_chapters: 551,
    official_links: [{ name: 'Official Site', url: 'https://example.com' }],
    translation_links: [{ name: 'Fan Translation', url: 'https://example.com' }],
    created_at: '2024-01-08T00:00:00Z',
    updated_at: '2024-01-08T00:00:00Z',
    created_by: null,
    regions: mockRegions[2],
    novel_genres: [
      { genres: mockGenres[0] },
      { genres: mockGenres[2] },
      { genres: mockGenres[7] },
      { genres: mockGenres[13] },
    ],
  },
  {
    id: '9',
    title: 'Mushoku Tensei',
    alternative_titles: ['無職転生', 'Jobless Reincarnation'],
    author: 'Rifujin na Magonote',
    region_id: 1,
    summary: 'A 34-year-old NEET gets killed in a traffic accident and finds himself in a world of magic. Rather than waking up as a full-grown mage, he is reincarnated as a newborn baby, retaining the memories of his past life.',
    cover_image_url: 'https://images.unsplash.com/photo-1618519764620-7403abdbdfe9?w=400&h=600&fit=crop',
    status: 'completed' as const,
    publication_year: 2012,
    total_chapters: 24,
    official_links: [{ name: 'Official Site', url: 'https://example.com' }],
    translation_links: [{ name: 'Fan Translation', url: 'https://example.com' }],
    created_at: '2024-01-09T00:00:00Z',
    updated_at: '2024-01-09T00:00:00Z',
    created_by: null,
    regions: mockRegions[0],
    novel_genres: [
      { genres: mockGenres[2] },
      { genres: mockGenres[1] },
      { genres: mockGenres[9] },
      { genres: mockGenres[7] },
    ],
  },
  {
    id: '10',
    title: 'Tales of Demons and Gods',
    alternative_titles: ['妖神记', 'Yao Shen Ji'],
    author: 'Mad Snail',
    region_id: 2,
    summary: 'Killed by a Sage Emperor and reborn as his 13 year old self, Nie Li was given a second chance at life. A second chance to change everything, save his loved ones and his beloved city from the insect tide.',
    cover_image_url: 'https://images.unsplash.com/photo-1614732414444-096e5f1122d5?w=400&h=600&fit=crop',
    status: 'hiatus' as const,
    publication_year: 2015,
    total_chapters: 490,
    official_links: null,
    translation_links: [{ name: 'Wuxiaworld', url: 'https://example.com' }],
    created_at: '2024-01-10T00:00:00Z',
    updated_at: '2024-01-10T00:00:00Z',
    created_by: null,
    regions: mockRegions[1],
    novel_genres: [
      { genres: mockGenres[0] },
      { genres: mockGenres[2] },
      { genres: mockGenres[10] },
      { genres: mockGenres[11] },
    ],
  },
  {
    id: '11',
    title: 'The Legendary Moonlight Sculptor',
    alternative_titles: ['달빛조각사', 'Dalbich Jogaksa'],
    author: 'Nam Heesung',
    region_id: 3,
    summary: 'The man forsaken by the world, the man a slave to money and the man known as the legendary God of War in the highly popular MMORPG Continent of Magic. With the coming of age, he decides to say goodbye, but the feeble attempt to earn a little something for his time.',
    cover_image_url: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=400&h=600&fit=crop',
    status: 'completed' as const,
    publication_year: 2007,
    total_chapters: 58,
    official_links: [{ name: 'Official Site', url: 'https://example.com' }],
    translation_links: [{ name: 'Fan Translation', url: 'https://example.com' }],
    created_at: '2024-01-11T00:00:00Z',
    updated_at: '2024-01-11T00:00:00Z',
    created_by: null,
    regions: mockRegions[2],
    novel_genres: [
      { genres: mockGenres[0] },
      { genres: mockGenres[1] },
      { genres: mockGenres[2] },
      { genres: mockGenres[6] },
    ],
  },
  {
    id: '12',
    title: 'A Will Eternal',
    alternative_titles: ['一念永恒', 'Yi Nian Yong Heng'],
    author: 'Er Gen',
    region_id: 2,
    summary: 'One will to create oceans. One will to summon the mulberry fields. One will to slaughter countless devils. One will to eradicate innumerable immortals. Only my will is eternal.',
    cover_image_url: 'https://images.unsplash.com/photo-1541963463532-d68292c34b19?w=400&h=600&fit=crop',
    status: 'completed' as const,
    publication_year: 2016,
    total_chapters: 1314,
    official_links: null,
    translation_links: [{ name: 'Wuxiaworld', url: 'https://example.com' }],
    created_at: '2024-01-12T00:00:00Z',
    updated_at: '2024-01-12T00:00:00Z',
    created_by: null,
    regions: mockRegions[1],
    novel_genres: [
      { genres: mockGenres[0] },
      { genres: mockGenres[2] },
      { genres: mockGenres[6] },
      { genres: mockGenres[10] },
    ],
  },
]
