export const mockReviews = [
  {
    id: 'review-1',
    user_id: 'user-1',
    novel_id: '1',
    rating: 5,
    title: 'A Groundbreaking Virtual Reality Story',
    content: 'Sword Art Online revolutionized the isekai genre with its unique take on virtual reality. The story is gripping, the characters are well-developed, and the world-building is exceptional. A must-read for any light novel fan.',
    is_spoiler: false,
    created_at: '2024-01-15T00:00:00Z',
    updated_at: '2024-01-15T00:00:00Z',
    profiles: { username: 'NovelFan123' },
  },
  {
    id: 'review-2',
    user_id: 'user-2',
    novel_id: '1',
    rating: 4,
    title: 'Great Start, Mixed Later Arcs',
    content: 'The Aincrad arc is phenomenal, but some later arcs feel rushed. Still, the overall experience is worth it. The romance subplot is handled well.',
    is_spoiler: false,
    created_at: '2024-01-16T00:00:00Z',
    updated_at: '2024-01-16T00:00:00Z',
    profiles: { username: 'CriticalReader' },
  },
  {
    id: 'review-3',
    user_id: 'user-3',
    novel_id: '4',
    rating: 5,
    title: 'The Best Power Fantasy',
    content: 'Solo Leveling delivers exactly what it promises - an incredible power fantasy with amazing action scenes. Sung Jin-Woo\'s journey from weakest to strongest is incredibly satisfying.',
    is_spoiler: false,
    created_at: '2024-01-17T00:00:00Z',
    updated_at: '2024-01-17T00:00:00Z',
    profiles: { username: 'ActionLover' },
  },
  {
    id: 'review-4',
    user_id: 'user-4',
    novel_id: '5',
    rating: 5,
    title: 'Emotional Rollercoaster',
    content: 'Re:Zero is not your typical isekai. It\'s dark, emotional, and incredibly well-written. Subaru\'s character development is some of the best I\'ve seen in any medium.',
    is_spoiler: false,
    created_at: '2024-01-18T00:00:00Z',
    updated_at: '2024-01-18T00:00:00Z',
    profiles: { username: 'EmotionalReader' },
  },
  {
    id: 'review-5',
    user_id: 'user-5',
    novel_id: '8',
    rating: 5,
    title: 'Meta Storytelling at Its Finest',
    content: 'ORV is a masterclass in meta-narrative. The way it plays with reader expectations and the concept of stories within stories is brilliant. Dokja is an amazing protagonist.',
    is_spoiler: false,
    created_at: '2024-01-19T00:00:00Z',
    updated_at: '2024-01-19T00:00:00Z',
    profiles: { username: 'MetaFan' },
  },
]
